### ISSUE TITLE
Unpack Error when using KFAC with block-diagonal for Dense networks

### ISSUE THREAD

**Issue by joeryjoery** [deepmind/kfac-jax#15]
Hi,

I was trying to get the example code in the readme working with the BlockDiagonal approximation. The default simply uses the normal diagonal. However, when I try to define my optimizer like this:

```python
opt = kfac_jax.Optimizer(
    value_and_grad_func=jax.value_and_grad(partial(expected_model_likelihood, l2=0.001)),
    l2_reg=0.001,
    use_adaptive_learning_rate=True,
    use_adaptive_damping=True,
    use_adaptive_momentum=True,
    initial_damping=1.0,
    min_damping= 0.0001,
    layer_tag_to_block_ctor={'generic_tag': kfac_jax.DenseTwoKroneckerFactored},  # Specify the approximation type here
    estimation_mode='ggn_curvature_prop',
    multi_device=False
)
```
then when I try to use this optimizer I get the following `ValueError`:
```python
del pmap_axis_name
x, = estimation_data["inputs"]
dy, = estimation_data["outputs_tangent"]
assert utils.first_dim_is_size(batch_size, x, dy)

ValueError: not enough values to unpack (expected 1, got 0)
```

Corresponding to the curvature update method in class `DenseTwoKroneckerFactored` (line 1165) of `_src.curvature_blocks.py`. The estimation data dictionary is filled with the parameters and parameters-tangents, but I do not understand the codebase sufficiently to grasp why the `inputs` and `outputs_tangent` keys are not filled.

In this way I cannot get the actual `KFAC` of this repo working... Are there perhaps some examples that make use of the `DenseTwoKroneckerFactored`? As far as I can tell all provided `examples` simply make use of the diagonal Fisher for optimization, not `KFAC`. But I may be wrong of course.

**Comment by botev** [comment]
Ok, so to understand this part you need a bit to read the advanced docs [here](https://kfac-jax.readthedocs.io/en/latest/advanced.html).

The way KFAC works is in two stages:
It first marks/labels certain computations with specific "layer_tags" and then separately to each tag it assigns a block class. 
The generic_tag is only compatible with `NaiveDiagonal` and `NaiveFull` curvature blocks, while the Dense blocks are compatible only with the dense_tag currently.

So what needs to happen, is you need to correctly have a dense tag computation in your model in order to be able to use the DenseTwoKroneckerFactored block. If this is not picked up automatically, you can in your code use manually `kfac_jax.register_dense` to manually register your computation as dense. 
I can't comment why it is not picked up automatically, without seeing your model code.

**Comment by botev** [comment]
PS: If you resolve your problem please do close the issue tracker.

**Comment by joeryjoery** [comment]
> Ok, so to understand this part you need a bit to read the advanced docs [here](https://kfac-jax.readthedocs.io/en/latest/advanced.html).
> 
> The way KFAC works is in two stages: It first marks/labels certain computations with specific "layer_tags" and then separately to each tag it assigns a block class. The generic_tag is only compatible with `NaiveDiagonal` and `NaiveFull` curvature blocks, while the Dense blocks are compatible only with the dense_tag currently.
> 
> So what needs to happen, is you need to correctly have a dense tag computation in your model in order to be able to use the DenseTwoKroneckerFactored block. If this is not picked up automatically, you can in your code use manually `kfac_jax.register_dense` to manually register your computation as dense. I can't comment why it is not picked up automatically, without seeing your model code.


Right, I see. I was using my own defined Dense layers using `hk.Module` and I assumed that the optimizer would recognize this automatically. My implementation is a bit different from `hk.Linear` as I was writing my own implementation for `KFAC`, and variants thereof, and I concatenated the bias vector into the weight matrix. Could this be the cause? 

Anyways, I can indeed get it working when I switch out my implementation for the `hk.Linear` modules. Your comment clears up my confusion! Thanks!
