### ISSUE TITLE
Quick question on "layer_tag_vjp" 

### ISSUE THREAD

**Issue by connection-on-fiber-bundles** [deepmind/kfac-jax#95]
Hey KFAC team,

First of all, thanks a lot for this awesome project and all the hard work!

Got a quick question on the implementation of `_layer_tag_vjp` function in "tracer.py". The version is 0.0.3.

For the returned function [vjp_func](https://github.com/deepmind/kfac-jax/blob/e3da81657996f7f66d2e69f8c45ef08bce1b9909/kfac_jax/_src/tracer.py#L724), my understanding is that it reads primal and tangent value of the "layer inputs" from previously constructed information, specifically `primals_dict` and `tangents_dict`. My questions are:
1. For "primal_dict", it not only contains info for all the layer input, but also contains info for the input of the whole jaxpr. See [here](https://github.com/deepmind/kfac-jax/blob/e3da81657996f7f66d2e69f8c45ef08bce1b9909/kfac_jax/_src/tracer.py#L710). It seems to me that the latter info is not needed here since we are only retrieving info for layer inputs in `vjp_func`. So is the latter info (about the input of the whole jaxpr) really necessary here, and why?
2. For "tangents_dict", it constructed from the `aux_vjp`. The [implementation](https://github.com/deepmind/kfac-jax/blob/e3da81657996f7f66d2e69f8c45ef08bce1b9909/kfac_jax/_src/tracer.py#L738) reads:
```
    all_tangents = aux_vjp(tangents)
    tangents_dict, inputs_tangents = all_tangents[0], all_tangents[1:]
    inputs_tangents = jax.tree_util.tree_leaves(inputs_tangents)
    tangents_dict.update(zip(processed_jaxpr.jaxpr.invars, inputs_tangents))
```
Here `aux_vjp` is the vjp function for `forward_aux` (See [here](https://github.com/deepmind/kfac-jax/blob/e3da81657996f7f66d2e69f8c45ef08bce1b9909/kfac_jax/_src/tracer.py#L718)). Therefore the output of `aux_vjp`, namely `all_tangents` should have the same structure as the input of `forward_aux`. Here `forward_aux` only has a single argument, and thus `all_tangents` should be just a tuple with a single element. If that's the case, then `inputs_tangents` is always empty, and we can simplify the implementation to 
```
tangents_dict, = aux_vjp(tangents)
```
Am I missing anything here? Or in which case will we have a non-empty `inputs_tangents`?

**Comment by botev** [comment]
1. So the additional information in the `primals_dict` (the inputs in particular) are for **most** practical purposes as you have observed not needed. This has been just let on to be there from convenience of modifying the code, since its quite cumbersome to always extract from the jaxpr only variables corresponding to parameters and outputs. 
2. Yes you are right, I think that part of code was probably used in the past for something, but is no longer needed. 

In general since this is **still** research code, we retain certain parts of the code, especially internal bits like the one you are looking at, even if they are no longer needed.

**Comment by connection-on-fiber-bundles** [comment]
Got it. Make sense. Thanks for the response!
